version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
      - npm ci
  build:
    commands:
      # run the build
      - echo "[+] Installing dependencies...."
      - ls -l
      - pip install flask
      - pip install -r requirements.txt
      - echo "[+] After installing dep...."
      - npm run build
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - package.json
    - appspec.yml
    - app.py
    - requirements.txt
    - 'node_modules/**/*'